FROM ubuntu:16.04

RUN apt-get update && apt-get install -y firefox \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN adduser --gecos "" --shell /bin/bash --disabled-password browser

USER browser
ENV HOME /home/browser
CMD /usr/bin/firefox
